### ISSUE TITLE
Kubernetes

### ISSUE THREAD

**Issue by tgeek77** [cmehay/docker-tor-hidden-service#14]
This isn't really an issue, but a question. Has anyone successfully used this container in Kubernetes and if so, how did you set it up?

**Comment by cmehay** [comment]
I'm not familiar yet with Kubernetes, so I'm afraid I will not be able to give you an answer, but feel free to send a patch to run this container in a Kubernetes cluster.

**Comment by AndreKoepke** [comment]
Pretty simple. Just place the environments-vars like in the https://github.com/cmehay/docker-tor-hidden-service/blob/master/README.md.

```
apiVersion: v1
kind: Pod
metadata:
  name: tor-expose
spec:
  restartPolicy: Never


  containers:
  - name: tor
    image: goldy/tor-hidden-service:latest
    env:
      - name: <SERVICE-NAME>_TOR_SERVICE_HOSTS
        value: "<EXPOSE-PORT>:<HOST>:<HOST-PORT>"
```
