### ISSUE TITLE
Problem using SSH docker `corbinu/ssh-server` image 

### ISSUE THREAD

**Issue by shivergard** [cmehay/docker-tor-hidden-service#19]
As I understand port 22 is not ready , when hidden service tries to set it using docker compose.
Any suggestions ?

**Comment by cmehay** [comment]
can you paste your compose file to reproduce ?

**Comment by shivergard** [comment]
https://gist.github.com/shivergard/db540771037cfbd2ce60e8629402d332

DockerCompose from ssh server Docker file : https://hub.docker.com/r/corbinu/ssh-server/~/dockerfile/

**Comment by cmehay** [comment]
Add quote around ports that should fix this issue:
```yaml
environment:
        # Set mapping ports
        SSH_PORTS: "22:22"
```
