### ISSUE TITLE
How do we use Unix sockets with new version?

### ISSUE THREAD

**Issue by lugshow** [cmehay/docker-tor-hidden-service#24]
Hello. My service works great with your legacy config but breaks with the new config.

Are unix sockets still supported like in the legacy example? This is a must for me. Can you please help me with an example on how to use on the new version?

**Comment by cmehay** [comment]
Unix sockets are still supported.

I forgot to add an example with socket on the new doc. The setup is similar:

```yaml
environment:
        # Set service hosts to unix socket
        WORLD_TOR_SERVICE_HOSTS: 80:unix://var/run/nginx.sock
```

I'll change the example in `docker-compose.v2.socket.yml` file.
