### ISSUE TITLE
Unable to make this works correctly

### ISSUE THREAD

**Issue by davidtavarez** [cmehay/docker-tor-hidden-service#29]
So, the container is running but I'm not able to access the hidden service.
![Screenshot from 2019-07-17 18-38-36](https://user-images.githubusercontent.com/337107/61416557-1458da80-a8c2-11e9-847e-2d6418e2bb90.png)

I'm able to access the other container from the `tor`.
![Screenshot from 2019-07-17 18-37-29](https://user-images.githubusercontent.com/337107/61416993-ac0af880-a8c3-11e9-8957-989a03468a99.png)

This is my `docker-compose.yml`:
```
version: '3'

services:
  tor:
    image: goldy/tor-hidden-service:0.4.0.5
    links:
      - safer
    hostname: onion
    environment:
      SAFER_TOR_SERVICE_HOSTS: 80:safer:56733
      SAFER_TOR_SERVICE_VERSION: 3
      SAFER_TOR_SERVICE_KEY: |
        PT0gZWQyNTUxOXYxLXNlY3JldDogdHlwZTAgPT0AAAB4Arvdx5kzsF8dK+OUDOSt
        13Zytck6JM1xxFp3ftGhRGlJTZ1X2wrztcqzXYuQftzxZXB0wTYwJl+cUVm3RmH7

  safer:
    build:
      context: ./
      dockerfile: Dockerfile
    image: safer
    volumes:
      ['./:/app']
    ports:
      ['56733:80']
    hostname: safer
```
