### ISSUE TITLE
Unable to deploy on docker swarm

### ISSUE THREAD

**Issue by venomone** [cmehay/docker-tor-hidden-service#45]
Hello,

if I try to deploy the hidden-service container on a docker swarm deployment I'm running into the following issue:

> Entrypoint WARNING  ERROR:root:Fail to setup from GPG_KEY environment
> Entrypoint WARNING  ERROR:root:Private key does not seems to be a valid RSA PEM key
> Entrypoint WARNING  ERROR:root:Service gpg has not ports set
> Entrypoint INFO     v3: jeirgjrjgiergerhgergherughphuhgperguherhgoeg.onion:80
> Jul 16 15:03:24.390 [notice] Tor 0.4.3.6 (git-30711296fd5b7f51) running on Linux with Libevent 2.1.11-stable, OpenSSL 1.1.1g, Zlib 1.2.11, Liblzma N/A, and Libzstd N/A.
> Jul 16 15:03:24.390 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
> Jul 16 15:03:24.390 [notice] Read configuration file "/etc/tor/torrc".
> Jul 16 15:03:24.000 [notice] Parsing GEOIP IPv4 file /usr/local/share/tor/geoip.
> Jul 16 15:03:24.000 [notice] Parsing GEOIP IPv6 file /usr/local/share/tor/geoip6.
> Jul 16 15:03:24.000 [notice] Bootstrapped 0% (starting): Starting
> Jul 16 15:03:24.000 [notice] Starting with guard context "default"
> Jul 16 15:03:25.000 [notice] Bootstrapped 5% (conn): Connecting to a relay
... END!?!

My docker-compose looks like this (version 3.5):
docker-compose.yml:

```
...
  onion-relay:
    image: goldy/tor-hidden-service:latest
    hostname: onion-relay
    networks:
      - onion
      - frontend
    environment:
      V3_TOR_SERVICE_HOSTS: 80:spice:80
      V3_TOR_SERVICE_VERSION: '3'
      V3_TOR_SERVICE_KEY: |
        PT0gZWSomeRandomShitldDogdHlwZTAgwoeifjiwefjiowefkjpwifmBlBlaBlaBlaWe7xEiPjIVvdvd
        0odmBX7deaa95r+va2+eObAwWDZ0Lgtziowefjiwefijfewfwe

...
```

Of course the real key is another. The funny thing is that exactly the same config is working locally for me but not on my swarm cluster?!? Any Idea as this makes no sense to me?
