### ISSUE TITLE
Issues on K8s

### ISSUE THREAD

**Issue by venomone** [cmehay/docker-tor-hidden-service#51]
I've been watching this project for a while now and it works like a charm on plain docker!
Now I'm switching over to k8s and trying to get this container up and running but I'm experiencing a strange behaviour.
As soon as my deployment is setup and I'm trying to access the service using the tor browser the connection gets  very often reset for some reason. Sometimes it's working, sometimes its not. I was not able to find anything useful statement on the logs and I would like to know if smb. else has the same issue and maybe also a solution or a hint where I could possibly look at.

This is how I deploy the service:

```
apiVersion: v1
kind: Pod
metadata:
  name: onion-web-relay-0
  namespace: app
  labels:
    app: app
    tier: frontend
spec:
  containers:
  - name: onion-web-relay
    image: goldy/tor-hidden-service:latest
    envFrom:
      - configMapRef:
          name: onion-env
    env:
      - name: V3_TOR_SERVICE_KEY
        valueFrom:
          secretKeyRef:
            name: onion-web-relay
            key: privat-crypto
    resources:
      requests:
        cpu: 500m
        memory: 1024Mi
      limits:
        cpu: 2000m
        memory: 2048Mi
```

Merci
