### ISSUE TITLE
What's the trick to use custom ed25519 keys?

### ISSUE THREAD

**Issue by graffen** [cmehay/docker-tor-hidden-service#60]
I'm trying to set up a hidden service using a custom ed25519 key. To get the base64 of the private key, I run `cat hs_ed25519_secret_key | base64` and create a `docker-compose.yml` based on README.md. However, I continue to get this error, and Tor just starts up with its own self-generated keypair (which subsequently works fine as I can connect to the HS through Tor).

```
tor_1         | Entrypoint WARNING  ERROR:root:Fail to setup from GPG_KEY environment
tor_1         | Entrypoint WARNING  ERROR:root:Private key does not seems to be a valid RSA PEM key
tor_1         | Entrypoint WARNING  ERROR:root:Fail to setup from GRAFFENDK_TOR_SERVICE_KEY environment
tor_1         | Entrypoint WARNING  ERROR:root:Private key does not seems to be a valid ed25519 tor key
tor_1         | Entrypoint WARNING  ERROR:root:Service gpg has not ports set
tor_1         | Entrypoint INFO     graffendk: qhsxyycredghviwmomq7dmlyqac6g4o2ivc567bqovgek6ur74tas2qd.onion:80
g
```

This is my current `docker-compose.yml` file: 

```
version: '3'

services:
  tor:
    image: goldy/tor-hidden-service:0.4.4.6
    links:
      - graffen.dk
    environment:
      GRAFFENDK_TOR_SERVICE_HOSTS: '80:graffen.dk:80'
      GRAFFENDK_TOR_SERVICE_VERSION: '3'
      GRAFFENDK_TOR_SERVICE_KEY: |
        OUTPUT_FROM_base64_COMMAND
        HERE
    networks:
      - tor

  graffen.dk:
    image: 'graffen.dk-website'
    environment:
      LETSENCRYPT_HOST: 'graffen.dk,www.graffen.dk'
      VIRTUAL_HOST: 'graffen.dk,www.graffen.dk'
      LETSENCRYPT_EMAIL: 'xxx`
    networks:
      - proxy_net
      - tor

networks:
  proxy_net:
    external:
      name: 'nextcloud-docker-compose_proxy-tier'
  tor:
```

Do I need to do something else to get the base64 version of the key or have I missed something different?
