### ISSUE TITLE
"Entrypoint INFO No onion site" when trying to link to Node Express server using docker-compose.yml

### ISSUE THREAD

**Issue by JaredDahlke** [cmehay/docker-tor-hidden-service#78]
Hey guys sorry for the noob question, but here we go:

I was able to successfully link goldy/tor-hidden-service on the command line using 2 commands:
```
docker run -d --name hello_world nodeserver
docker run -ti --link hello_world goldy/tor-hidden-service
```

When i run that, it successfully generates ands logs a public onion URL that exposes nodeserver.

Now when i try to do the same thing in docker-compose.yml,  nodeserver and tor run successfully, but there is no onion site generated. Here is my docker-compose.yml:

```
version: '2'
services:
  tor:
    image: goldy/tor-hidden-service
    links:
      - nodeserver
  nodeserver:
    image: jadahlke/peerjsonshare
    hostname: nodeserver
```

And here is the logging I get when I run docker-compose up:
```
Creating network "peerfileshare_default" with the default driver
Creating peerfileshare_nodeserver_1 ... done
Creating peerfileshare_tor_1        ... done
Attaching to peerfileshare_nodeserver_1, peerfileshare_tor_1
nodeserver_1  | listening on port 3009
tor_1         | Entrypoint INFO     No onion site                         ******** <---- THIS IS WHERE I AM EXPECTING TO SEE URL****
tor_1         | Jan 07 14:31:33.275 [notice] Tor 0.4.6.9 (git-ea2ada6d1459f829) running on Linux with Libevent 2.1.12-stable, OpenSSL 1.1.1l, Zlib 1.2.11, Liblzma N/A, Libzstd N/A and Unknown N/A as libc.
```

Would greatly appreciate if someone could point me in the right direction.
