### ISSUE TITLE
Tor Service unreachable, receiving dropped cell error while running vanguards

### ISSUE THREAD

**Issue by anoduck** [cmehay/docker-tor-hidden-service#80]
Regardless whether vanguards is enabled or not, my service is unreachable. It is only when vanguards is enabled that an error is received stating a circuit has been forced closed. The full output is as follows:
```sh
WARNING[Wed Feb xx xx:xx:xx xxxx]: Possible Tor bug, or possible attack if very frequent: Got 1 dropped cell on circ 69 (in state HS_SERVICE_REND HSSR_JOINED; old state HS_SERVICE_REND HSSR_CONNECTING)
NOTICE[Wed Feb xx xx:xx:xx xxxx]: We force-closed circuit 69
```
This is my docker-compose setup for the tor service:
```yaml
tor:
    image: goldy/tor-hidden-service:latest
    container_name: tor_container
    environment:
      TOR_ENABLE_VANGUARDS: 'true'
      VANGUARDS_EXTRA_OPTIONS: |
        [GLOBAL]
        enable_cbtverify = True

      CHAN_TOR_SERVICE_HOSTS: '{$TOR_PORT}:0.0.0.0:{$SERVICE_PORT}'
      CHAN_TOR_SERVICE_PORTS: '{$TOR_PORT}:{$SERVICE_PORT}'
      CHAN_TOR_SERVICE_VERSION: '3'
      CHAN_TOR_SERVICE_KEY: |
        '{$MY_BIG_LONG_KEY}'
    volumes:
      - type: bind
        source: ./tor
        target: /var/lib/tor/hidden_service
      - type: bind
        source: ./tor-data
        target: /run/tor/data
    secrets:
      - tor_secret
    networks:
      a_net:
        aliases:
          - tor
        ipv4_address: 0.0.0.0
    ports:
      - 9050:9050
```

As you can see, it does not appear that anything is wrong with the docker-compose.yml file, yet my client is still unreachable. Not sure what the received error is about. The only thing I can think of is if tor needs a larger dedicated shm_size.
